### ISSUE TITLE
Use Existing Service Account

### ISSUE THREAD

**Issue by sanath-2024** [deepmind/xmanager#26]
I am trying to use XManager with Vertex AI but do not have permissions to create a new service account. I noticed that the service account name is hard-coded to "xmanager" here:

https://github.com/deepmind/xmanager/blob/6b748270894ee2ca3499710620574eca2aa62ef0/xmanager/cloud/auth.py#L70-L92

Is it possible to add an option or parameter so that we can specify an existing service account name for XManager to use? Thanks.

**Comment by thesstefan** [comment]
After f9dafbb995b8e96140ae1ca8ed5b9f0b1f1b29b, specifying a custom service account is done by using the `--xm_service_account_name` flag.

**Comment by sanath-2024** [comment]
Thanks, this fixed the issue!
