### ISSUE TITLE
Any plan to open source additional experiment tracking tools in xmanager?

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/xmanager#7]
Hi,

Thanks a lot for open sourcing this! I believe that this would be really useful for the community.

Although I am not using xmanager at the moment (due to unfortunate constraints with university cluster compute environments), I would very much like to know if there are plans to open source other parts of xmanager. e.g. experiment tracking functionalities such as tracking measurements in an experiment (similar to TensorBoard I suppose?) and higher-level APIs for creating sweeps 
(e.g., https://github.com/google-research/dice_rl/blob/7f02659f027dd3b562ce8f628e10d74e28986795/google/scripts/xm_run_q_estimator.py#L82). I think open-sourcing these tools would provide immense value for the community!

Best,
Yicheng

**Comment by kibergus** [comment]
There are no short-term plans for open-sourcing these. For metrics we suggest using [Tensorboard](https://cloud.google.com/vertex-ai/docs/experiments/tensorboard-overview)
Example how to configure it: https://github.com/deepmind/xmanager/blob/6c0057040bb060bd29c787e0adfe40ce7d5b6c6e/examples/cifar10_tensorflow/launcher.py#L67

There are no plans for making API for defining sweeps part of XM launch API. We suggest using [Vertex Vizier](https://cloud.google.com/vertex-ai/docs/vizier/overview) for this.
