### ISSUE TITLE
googleapiclient.errors.UnknownApiNameOrVersion: name: us-central1-aiplatform  version: v1

### ISSUE THREAD

**Issue by JohanSamir** [deepmind/xmanager#8]
Hello,
I am trying to run some experiments using xmanager on a VM instance from Google Cloud. When I run the scrip i get the following error: 

_... raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: us-central1-aiplatform  version: v1_

![Screenshot from 2022-01-11 14-30-04](https://user-images.githubusercontent.com/33340952/149011033-21382051-73a7-401a-b748-0b75862a266e.png)

Any idea about this problem? Thanks in advance.

**Comment by andrewluchen** [comment]
This should not be occurring since https://github.com/deepmind/xmanager/commit/9c2043def8ebe0d0a54b6f76207624371e95ee2d

Since this change, we are using the official Vertex AI SDK and not googleapiclient.
