### ISSUE TITLE
enable_web_access for Vertex AI jobs

### ISSUE THREAD

**Issue by DzvinkaYarish** [deepmind/xmanager#9]
Hi, is there a way to launch Vertex AI jobs with enabled access to an interactive shell (https://cloud.google.com/vertex-ai/docs/training/monitor-debug-interactive-shell#vertexai_enable_web_access-python)?

**Comment by andrewluchen** [comment]
This looks like a straightforward change. At `run()`:

https://github.com/deepmind/xmanager/blob/main/xmanager/cloud/vertex.py#L191

We need to pass `enable_web_access` from

https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/jobs.py#L1337

**Comment by andrewluchen** [comment]
See
https://github.com/deepmind/xmanager/commit/1b95fd9e79a9801a7f58e61f928233ec5f877d79
